### ISSUE TITLE
Task - CPU Instruction Set [0x00 - 0xFF]

### ISSUE THREAD

**Issue by Ciaxur** [Ciaxur/yagb-emu#4]
## Task - CPU Instruction Set
Write up the Functionality of the CPU Instructions under the [`CPU Class`](https://github.com/Ciaxur/yagb-emu/blob/8e8fbcae/include/CPU.h)

**Given Tasks**
* [ ] Instructions 0x00 - 0x7F
* [ ] Instructions 0x10 - 0x1F
* [ ] Instructions 0x20 - 0x2F
* [ ] Instructions 0x30 - 0x3F
* [ ] Instructions 0x40 - 0x4F
* [ ] Instructions 0x50 - 0x5F
* [ ] Instructions 0x60 - 0x6F
* [ ] Instructions 0x70 - 0x7F
* [ ] Instructions 0x80 - 0x8F
* [ ] Instructions 0x90 - 0x9F
* [ ] Instructions 0xA0 - 0xAF
* [ ] Instructions 0xB0 - 0xBF
* [ ] Instructions 0xC0 - 0xCF
* [ ] Instructions 0xD0 - 0xDF
* [ ] Instructions 0xE0 - 0xEF
* [ ] Instructions 0xF0 - 0xFF

**References Used**
- [Opcode Table](https://gbdev.io/gb-opcodes/optables/)
- [Pandocs - CPU Instruction Set](https://bgb.bircd.org/pandocs.htm#cpuinstructionset)
- [CPU Opcode Reference](https://rednex.github.io/rgbds/gbz80.7.html)
